on:
  push:
    tags:
      - "site*"

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.1
      - uses: actions/setup-node@v3
        with:
          node-version: "16.x"
          cache: pnpm

